//! Ergonomic, value-oriented representations of BMP390 registers.
//!
//! The types in this module convert to and from the bit-level register field
//! sets generated by [`device_driver`](https://docs.rs/device-driver). They do
//! not perform device I/O; use [`crate::Bmp390::device`] for that. Converting an
//! ergonomic value to a generated field set initializes all bits not represented
//! by the ergonomic type to zero.

mod calibration;
mod command;
mod error_status;
mod event;
mod fifo_config;
mod iir_filter_config;
mod interface_config;
mod interrupt_control;
mod interrupt_status;
mod output_data_rate;
mod oversampling;
mod power_control;
mod status;

pub use calibration::Coefficients;
pub use command::{Command, CommandRegister};
pub use error_status::ErrorStatus;
pub use event::Event;
pub use fifo_config::{FifoConfig, FifoDataSelect, FifoMode, FifoSubsampling, FifoWatermark};
pub use iir_filter_config::FilterCoefficient;
pub use interface_config::{I2cWatchdogPeriod, InterfaceConfig, SpiMode};
pub use interrupt_control::{InterruptControl, InterruptLevel, InterruptOutput};
pub use interrupt_status::InterruptStatus;
pub use output_data_rate::OutputDataRate;
pub use oversampling::{Oversampling, OversamplingConfig};
pub use power_control::{PowerControl, PowerMode};
pub use status::Status;

use thiserror::Error;

/// An error caused by a reserved register value that has no ergonomic variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[error("reserved value {value} in register field {field}")]
pub struct ReservedValueError {
    /// The field containing the reserved value.
    pub field: &'static str,

    /// The reserved value.
    pub value: u8,
}

impl ReservedValueError {
    const fn new(field: &'static str, value: u8) -> Self {
        Self { field, value }
    }
}
