//! Ergonomic, value-oriented representations of BMP390 registers.
//!
//! The types in this module convert to and from the bit-level register field
//! sets generated by [`device_driver`](https://docs.rs/device-driver). They do
//! not perform device I/O; use [`crate::Bmp390::device`] for that. Converting an
//! ergonomic value to a generated field set initializes all bits not represented
//! by the ergonomic type to zero.

use crate::raw::{self, field_sets};
use thiserror::Error;

/// An error caused by a reserved register value that has no ergonomic variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[error("reserved value {value} in register field {field}")]
pub struct ReservedValueError {
    /// The field containing the reserved value.
    pub field: &'static str,

    /// The reserved value.
    pub value: u8,
}

impl ReservedValueError {
    const fn new(field: &'static str, value: u8) -> Self {
        Self { field, value }
    }
}

/// Sensor error conditions from [`field_sets::ErrReg`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct ErrorStatus {
    /// Whether the sensor has encountered a fatal error.
    pub fatal: bool,

    /// Whether command execution failed. Cleared on read.
    pub command: bool,

    /// Whether the sensor configuration is invalid. Cleared on read.
    pub configuration: bool,
}

impl From<field_sets::ErrReg> for ErrorStatus {
    fn from(value: field_sets::ErrReg) -> Self {
        Self {
            fatal: value.fatal_err(),
            command: value.cmd_err(),
            configuration: value.conf_err(),
        }
    }
}

impl From<ErrorStatus> for field_sets::ErrReg {
    fn from(value: ErrorStatus) -> Self {
        let mut register = Self::new_zero();
        register.set_fatal_err(value.fatal);
        register.set_cmd_err(value.command);
        register.set_conf_err(value.configuration);
        register
    }
}

/// Sensor status flags from [`field_sets::Status`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct Status {
    /// Whether the command decoder can accept a command.
    pub command_ready: bool,

    /// Whether new pressure data is available.
    pub pressure_ready: bool,

    /// Whether new temperature data is available.
    pub temperature_ready: bool,
}

impl From<field_sets::Status> for Status {
    fn from(value: field_sets::Status) -> Self {
        Self {
            command_ready: value.command_ready() == raw::CommandStatus::Ready,
            pressure_ready: value.data_ready_pressure(),
            temperature_ready: value.data_ready_temperature(),
        }
    }
}

impl From<Status> for field_sets::Status {
    fn from(value: Status) -> Self {
        let mut register = Self::new_zero();
        register.set_command_ready(if value.command_ready {
            raw::CommandStatus::Ready
        } else {
            raw::CommandStatus::InProgress
        });

        register.set_data_ready_pressure(value.pressure_ready);
        register.set_data_ready_temperature(value.temperature_ready);
        register
    }
}

/// Event flags from [`field_sets::Event`]. These flags are cleared on read.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct Event {
    /// Whether a power-on reset was detected.
    pub power_on_reset: bool,

    /// Whether an interface transaction occurred during a conversion.
    pub interface_activity: bool,
}

impl From<field_sets::Event> for Event {
    fn from(value: field_sets::Event) -> Self {
        Self {
            power_on_reset: value.por_detected(),
            interface_activity: value.itf_act_pt(),
        }
    }
}

impl From<Event> for field_sets::Event {
    fn from(value: Event) -> Self {
        let mut register = Self::new_zero();
        register.set_por_detected(value.power_on_reset);
        register.set_itf_act_pt(value.interface_activity);
        register
    }
}

/// Interrupt flags from [`field_sets::IntStatus`]. These flags are cleared on read.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct InterruptStatus {
    /// Whether the FIFO watermark interrupt is active.
    pub fifo_watermark: bool,

    /// Whether the FIFO full interrupt is active.
    pub fifo_full: bool,

    /// Whether the data-ready interrupt is active.
    pub data_ready: bool,
}

impl From<field_sets::IntStatus> for InterruptStatus {
    fn from(value: field_sets::IntStatus) -> Self {
        Self {
            fifo_watermark: value.fifo_full_watermark(),
            fifo_full: value.fifo_full(),
            data_ready: value.data_ready(),
        }
    }
}

impl From<InterruptStatus> for field_sets::IntStatus {
    fn from(value: InterruptStatus) -> Self {
        let mut register = Self::new_zero();
        register.set_fifo_full_watermark(value.fifo_watermark);
        register.set_fifo_full(value.fifo_full);
        register.set_data_ready(value.data_ready);
        register
    }
}

/// Electrical output mode for the interrupt pin.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum InterruptOutput {
    /// Push-pull output.
    PushPull,

    /// Open-drain output.
    OpenDrain,
}

impl From<raw::IntOpenDrain> for InterruptOutput {
    fn from(value: raw::IntOpenDrain) -> Self {
        match value {
            raw::IntOpenDrain::PushPull => Self::PushPull,
            raw::IntOpenDrain::OpenDrain => Self::OpenDrain,
        }
    }
}

impl From<InterruptOutput> for raw::IntOpenDrain {
    fn from(value: InterruptOutput) -> Self {
        match value {
            InterruptOutput::PushPull => Self::PushPull,
            InterruptOutput::OpenDrain => Self::OpenDrain,
        }
    }
}

/// Active level for the interrupt pin.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum InterruptLevel {
    /// Active low.
    ActiveLow,

    /// Active high.
    ActiveHigh,
}

impl From<raw::IntLevel> for InterruptLevel {
    fn from(value: raw::IntLevel) -> Self {
        match value {
            raw::IntLevel::ActiveLow => Self::ActiveLow,
            raw::IntLevel::ActiveHigh => Self::ActiveHigh,
        }
    }
}

impl From<InterruptLevel> for raw::IntLevel {
    fn from(value: InterruptLevel) -> Self {
        match value {
            InterruptLevel::ActiveLow => Self::ActiveLow,
            InterruptLevel::ActiveHigh => Self::ActiveHigh,
        }
    }
}

/// Interrupt configuration represented by [`field_sets::IntCtrl`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct InterruptControl {
    /// Electrical output mode for the interrupt pin.
    pub output: InterruptOutput,

    /// Active level for the interrupt pin.
    pub level: InterruptLevel,

    /// Whether the interrupt remains latched until cleared.
    pub latched: bool,

    /// Whether the FIFO watermark interrupt is enabled.
    pub fifo_watermark_enabled: bool,

    /// Whether the FIFO full interrupt is enabled.
    pub fifo_full_enabled: bool,

    /// Interrupt drive-strength selection.
    pub drive_strength: bool,

    /// Whether the pressure and temperature data-ready interrupt is enabled.
    pub data_ready_enabled: bool,
}

impl From<field_sets::IntCtrl> for InterruptControl {
    fn from(value: field_sets::IntCtrl) -> Self {
        Self {
            output: value.int_open_drain().into(),
            level: value.int_level().into(),
            latched: value.int_latch(),
            fifo_watermark_enabled: value.fifo_watermark_int_enable(),
            fifo_full_enabled: value.fifo_full_int_enable(),
            drive_strength: value.int_ds(),
            data_ready_enabled: value.data_ready_int_enable(),
        }
    }
}

impl From<InterruptControl> for field_sets::IntCtrl {
    fn from(value: InterruptControl) -> Self {
        let mut register = Self::new_zero();
        register.set_int_open_drain(value.output.into());
        register.set_int_level(value.level.into());
        register.set_int_latch(value.latched);
        register.set_fifo_watermark_int_enable(value.fifo_watermark_enabled);
        register.set_fifo_full_int_enable(value.fifo_full_enabled);
        register.set_int_ds(value.drive_strength);
        register.set_data_ready_int_enable(value.data_ready_enabled);
        register
    }
}

/// Sensor measurement mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum PowerMode {
    /// No measurements are performed.
    Sleep,

    /// One forced measurement is performed before returning to sleep.
    Forced,

    /// Measurements are performed continuously at the configured rate.
    Normal,
}

impl From<raw::MeasurementMode> for PowerMode {
    fn from(value: raw::MeasurementMode) -> Self {
        match value {
            raw::MeasurementMode::Sleep => Self::Sleep,
            raw::MeasurementMode::Forced => Self::Forced,
            raw::MeasurementMode::Forced2 => Self::Forced,
            raw::MeasurementMode::Normal => Self::Normal,
        }
    }
}

impl From<PowerMode> for raw::MeasurementMode {
    fn from(value: PowerMode) -> Self {
        match value {
            PowerMode::Sleep => Self::Sleep,
            PowerMode::Forced => Self::Forced,
            PowerMode::Normal => Self::Normal,
        }
    }
}

/// Power and measurement configuration represented by [`field_sets::PwrCtrl`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct PowerControl {
    /// Whether pressure measurements are enabled.
    pub pressure_enabled: bool,

    /// Whether temperature measurements are enabled.
    pub temperature_enabled: bool,

    /// Sensor measurement mode.
    pub mode: PowerMode,
}

impl From<field_sets::PwrCtrl> for PowerControl {
    fn from(value: field_sets::PwrCtrl) -> Self {
        Self {
            pressure_enabled: value.pressure_enable(),
            temperature_enabled: value.temperature_enable(),
            mode: value.mode().into(),
        }
    }
}

impl From<PowerControl> for field_sets::PwrCtrl {
    fn from(value: PowerControl) -> Self {
        let mut register = Self::new_zero();
        register.set_pressure_enable(value.pressure_enabled);
        register.set_temperature_enable(value.temperature_enabled);
        register.set_mode(value.mode.into());
        register
    }
}

/// Oversampling applied to a measurement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Oversampling {
    /// No oversampling.
    X1,

    /// 2x oversampling.
    X2,

    /// 4x oversampling.
    X4,

    /// 8x oversampling.
    X8,

    /// 16x oversampling.
    X16,

    /// 32x oversampling.
    X32,
}

impl TryFrom<raw::Oversampling> for Oversampling {
    type Error = ReservedValueError;

    fn try_from(value: raw::Oversampling) -> Result<Self, Self::Error> {
        match value {
            raw::Oversampling::X1 => Ok(Self::X1),
            raw::Oversampling::X2 => Ok(Self::X2),
            raw::Oversampling::X4 => Ok(Self::X4),
            raw::Oversampling::X8 => Ok(Self::X8),
            raw::Oversampling::X16 => Ok(Self::X16),
            raw::Oversampling::X32 => Ok(Self::X32),
            raw::Oversampling::Reserved(value) => {
                Err(ReservedValueError::new("oversampling", value))
            }
        }
    }
}

impl From<Oversampling> for raw::Oversampling {
    fn from(value: Oversampling) -> Self {
        match value {
            Oversampling::X1 => Self::X1,
            Oversampling::X2 => Self::X2,
            Oversampling::X4 => Self::X4,
            Oversampling::X8 => Self::X8,
            Oversampling::X16 => Self::X16,
            Oversampling::X32 => Self::X32,
        }
    }
}

/// Pressure and temperature oversampling represented by [`field_sets::Osr`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct OversamplingConfig {
    /// Pressure oversampling.
    pub pressure: Oversampling,

    /// Temperature oversampling.
    pub temperature: Oversampling,
}

impl TryFrom<field_sets::Osr> for OversamplingConfig {
    type Error = ReservedValueError;

    fn try_from(value: field_sets::Osr) -> Result<Self, Self::Error> {
        let pressure = value
            .pressure()
            .try_into()
            .map_err(|error: ReservedValueError| {
                ReservedValueError::new("osr.pressure", error.value)
            })?;

        let temperature = value
            .temperature()
            .try_into()
            .map_err(|error: ReservedValueError| {
                ReservedValueError::new("osr.temperature", error.value)
            })?;

        Ok(Self {
            pressure,
            temperature,
        })
    }
}

impl From<OversamplingConfig> for field_sets::Osr {
    fn from(value: OversamplingConfig) -> Self {
        let mut register = Self::new_zero();
        register.set_pressure(value.pressure.into());
        register.set_temperature(value.temperature.into());
        register
    }
}

/// Output data rate for pressure and temperature measurements.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum OutputDataRate {
    /// 200 Hz, 5 ms sampling period, prescaler 1.
    Hz200,

    /// 100 Hz, 10 ms sampling period, prescaler 2.
    Hz100,

    /// 50 Hz, 20 ms sampling period, prescaler 4.
    Hz50,

    /// 25 Hz, 40 ms sampling period, prescaler 8.
    Hz25,

    /// 25/2 Hz, 80 ms sampling period, prescaler 16.
    Hz12P5,

    /// 25/4 Hz, 160 ms sampling period, prescaler 32.
    Hz6P25,

    /// 25/8 Hz, 320 ms sampling period, prescaler 64.
    Hz3P1,

    /// 25/16 Hz, 640 ms sampling period, prescaler 128.
    Hz1P5,

    /// 25/32 Hz, 1.280 s sampling period, prescaler 256.
    Hz0P78,

    /// 25/64 Hz, 2.560 s sampling period, prescaler 512.
    Hz0P39,

    /// 25/128 Hz, 5.120 s sampling period, prescaler 1024.
    Hz0P2,

    /// 25/256 Hz, 10.24 s sampling period, prescaler 2048.
    Hz0P1,

    /// 25/512 Hz, 20.48 s sampling period, prescaler 4096.
    Hz0P05,

    /// 25/1024 Hz, 40.96 s sampling period, prescaler 8192.
    Hz0P02,

    /// 25/2048 Hz, 81.92 s sampling period, prescaler 16384.
    Hz0P01,

    /// 25/4096 Hz, 163.84 s sampling period, prescaler 32768.
    Hz0P006,

    /// 25/8192 Hz, 327.68 s sampling period, prescaler 65536.
    Hz0P003,

    /// 25/16384 Hz, 655.36 s sampling period, prescaler 131072.
    Hz0P0015,
}

impl TryFrom<raw::OdrSel> for OutputDataRate {
    type Error = ReservedValueError;

    fn try_from(value: raw::OdrSel) -> Result<Self, Self::Error> {
        match value {
            raw::OdrSel::Odr200 => Ok(Self::Hz200),
            raw::OdrSel::Odr100 => Ok(Self::Hz100),
            raw::OdrSel::Odr50 => Ok(Self::Hz50),
            raw::OdrSel::Odr25 => Ok(Self::Hz25),
            raw::OdrSel::Odr12P5 => Ok(Self::Hz12P5),
            raw::OdrSel::Odr6P25 => Ok(Self::Hz6P25),
            raw::OdrSel::Odr3P1 => Ok(Self::Hz3P1),
            raw::OdrSel::Odr1P5 => Ok(Self::Hz1P5),
            raw::OdrSel::Odr0P78 => Ok(Self::Hz0P78),
            raw::OdrSel::Odr0P39 => Ok(Self::Hz0P39),
            raw::OdrSel::Odr0P2 => Ok(Self::Hz0P2),
            raw::OdrSel::Odr0P1 => Ok(Self::Hz0P1),
            raw::OdrSel::Odr0P05 => Ok(Self::Hz0P05),
            raw::OdrSel::Odr0P02 => Ok(Self::Hz0P02),
            raw::OdrSel::Odr0P01 => Ok(Self::Hz0P01),
            raw::OdrSel::Odr0P006 => Ok(Self::Hz0P006),
            raw::OdrSel::Odr0P003 => Ok(Self::Hz0P003),
            raw::OdrSel::Odr0P0015 => Ok(Self::Hz0P0015),
            raw::OdrSel::Reserved(value) => Err(ReservedValueError::new("odr.odr_sel", value)),
        }
    }
}

impl From<OutputDataRate> for raw::OdrSel {
    fn from(value: OutputDataRate) -> Self {
        match value {
            OutputDataRate::Hz200 => Self::Odr200,
            OutputDataRate::Hz100 => Self::Odr100,
            OutputDataRate::Hz50 => Self::Odr50,
            OutputDataRate::Hz25 => Self::Odr25,
            OutputDataRate::Hz12P5 => Self::Odr12P5,
            OutputDataRate::Hz6P25 => Self::Odr6P25,
            OutputDataRate::Hz3P1 => Self::Odr3P1,
            OutputDataRate::Hz1P5 => Self::Odr1P5,
            OutputDataRate::Hz0P78 => Self::Odr0P78,
            OutputDataRate::Hz0P39 => Self::Odr0P39,
            OutputDataRate::Hz0P2 => Self::Odr0P2,
            OutputDataRate::Hz0P1 => Self::Odr0P1,
            OutputDataRate::Hz0P05 => Self::Odr0P05,
            OutputDataRate::Hz0P02 => Self::Odr0P02,
            OutputDataRate::Hz0P01 => Self::Odr0P01,
            OutputDataRate::Hz0P006 => Self::Odr0P006,
            OutputDataRate::Hz0P003 => Self::Odr0P003,
            OutputDataRate::Hz0P0015 => Self::Odr0P0015,
        }
    }
}

/// Output data rate configuration represented by [`field_sets::Odr`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct OutputDataRateConfig {
    /// Pressure and temperature output data rate.
    pub rate: OutputDataRate,
}

impl TryFrom<field_sets::Odr> for OutputDataRateConfig {
    type Error = ReservedValueError;

    fn try_from(value: field_sets::Odr) -> Result<Self, Self::Error> {
        Ok(Self {
            rate: value.odr_sel().try_into()?,
        })
    }
}

impl From<OutputDataRateConfig> for field_sets::Odr {
    fn from(value: OutputDataRateConfig) -> Self {
        let mut register = Self::new_zero();
        register.set_odr_sel(value.rate.into());
        register
    }
}

/// IIR filter coefficient.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum FilterCoefficient {
    /// Bypass mode.
    Coefficient0,

    /// Coefficient 1.
    Coefficient1,

    /// Coefficient 3.
    Coefficient3,

    /// Coefficient 7.
    Coefficient7,

    /// Coefficient 15.
    Coefficient15,

    /// Coefficient 31.
    Coefficient31,

    /// Coefficient 63.
    Coefficient63,

    /// Coefficient 127.
    Coefficient127,
}

impl From<raw::IirFilterCoefficient> for FilterCoefficient {
    fn from(value: raw::IirFilterCoefficient) -> Self {
        match value {
            raw::IirFilterCoefficient::Coef0 => Self::Coefficient0,
            raw::IirFilterCoefficient::Coef1 => Self::Coefficient1,
            raw::IirFilterCoefficient::Coef3 => Self::Coefficient3,
            raw::IirFilterCoefficient::Coef7 => Self::Coefficient7,
            raw::IirFilterCoefficient::Coef15 => Self::Coefficient15,
            raw::IirFilterCoefficient::Coef31 => Self::Coefficient31,
            raw::IirFilterCoefficient::Coef63 => Self::Coefficient63,
            raw::IirFilterCoefficient::Coef127 => Self::Coefficient127,
        }
    }
}

impl From<FilterCoefficient> for raw::IirFilterCoefficient {
    fn from(value: FilterCoefficient) -> Self {
        match value {
            FilterCoefficient::Coefficient0 => Self::Coef0,
            FilterCoefficient::Coefficient1 => Self::Coef1,
            FilterCoefficient::Coefficient3 => Self::Coef3,
            FilterCoefficient::Coefficient7 => Self::Coef7,
            FilterCoefficient::Coefficient15 => Self::Coef15,
            FilterCoefficient::Coefficient31 => Self::Coef31,
            FilterCoefficient::Coefficient63 => Self::Coef63,
            FilterCoefficient::Coefficient127 => Self::Coef127,
        }
    }
}

/// IIR filter configuration represented by [`field_sets::Config`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct IirFilterConfig {
    /// IIR filter coefficient.
    pub coefficient: FilterCoefficient,
}

impl From<field_sets::Config> for IirFilterConfig {
    fn from(value: field_sets::Config) -> Self {
        Self {
            coefficient: value.iir_filter().into(),
        }
    }
}

impl From<IirFilterConfig> for field_sets::Config {
    fn from(value: IirFilterConfig) -> Self {
        let mut register = Self::new_zero();
        register.set_iir_filter(value.coefficient.into());
        register
    }
}

/// Command accepted by the BMP390 command register.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Command {
    /// No operation.
    Nop,

    /// Clear all FIFO data.
    FlushFifo,

    /// Reset the device and its user configuration.
    SoftReset,
}

impl TryFrom<raw::Command> for Command {
    type Error = ReservedValueError;

    fn try_from(value: raw::Command) -> Result<Self, Self::Error> {
        match value {
            raw::Command::Nop => Ok(Self::Nop),
            raw::Command::FifoFlush => Ok(Self::FlushFifo),
            raw::Command::SoftReset => Ok(Self::SoftReset),
            raw::Command::Reserved(value) => Err(ReservedValueError::new("cmd.cmd", value)),
        }
    }
}

impl From<Command> for raw::Command {
    fn from(value: Command) -> Self {
        match value {
            Command::Nop => Self::Nop,
            Command::FlushFifo => Self::FifoFlush,
            Command::SoftReset => Self::SoftReset,
        }
    }
}

/// Command register value represented by [`field_sets::CmdFieldsIn`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct CommandRegister {
    /// Command to execute.
    pub command: Command,
}

impl TryFrom<field_sets::CmdFieldsIn> for CommandRegister {
    type Error = ReservedValueError;

    fn try_from(value: field_sets::CmdFieldsIn) -> Result<Self, Self::Error> {
        Ok(Self {
            command: value.cmd().try_into()?,
        })
    }
}

impl From<CommandRegister> for field_sets::CmdFieldsIn {
    fn from(value: CommandRegister) -> Self {
        let mut register = Self::new_zero();
        register.set_cmd(value.command.into());
        register
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn infallible_registers_round_trip() {
        let errors = ErrorStatus {
            fatal: true,
            command: false,
            configuration: true,
        };
        assert_eq!(ErrorStatus::from(field_sets::ErrReg::from(errors)), errors);

        let status = Status {
            command_ready: true,
            pressure_ready: false,
            temperature_ready: true,
        };
        assert_eq!(Status::from(field_sets::Status::from(status)), status);

        let event = Event {
            power_on_reset: false,
            interface_activity: true,
        };
        assert_eq!(Event::from(field_sets::Event::from(event)), event);

        let interrupt_status = InterruptStatus {
            fifo_watermark: true,
            fifo_full: false,
            data_ready: true,
        };
        assert_eq!(
            InterruptStatus::from(field_sets::IntStatus::from(interrupt_status)),
            interrupt_status
        );

        let interrupt_control = InterruptControl {
            output: InterruptOutput::OpenDrain,
            level: InterruptLevel::ActiveLow,
            latched: true,
            fifo_watermark_enabled: false,
            fifo_full_enabled: true,
            drive_strength: false,
            data_ready_enabled: true,
        };
        assert_eq!(
            InterruptControl::from(field_sets::IntCtrl::from(interrupt_control)),
            interrupt_control
        );

        let power = PowerControl {
            pressure_enabled: true,
            temperature_enabled: false,
            mode: PowerMode::Forced,
        };
        assert_eq!(PowerControl::from(field_sets::PwrCtrl::from(power)), power);

        let filter = IirFilterConfig {
            coefficient: FilterCoefficient::Coefficient31,
        };
        assert_eq!(
            IirFilterConfig::from(field_sets::Config::from(filter)),
            filter
        );
    }

    #[test]
    fn fallible_registers_round_trip() {
        let oversampling = OversamplingConfig {
            pressure: Oversampling::X2,
            temperature: Oversampling::X16,
        };
        assert_eq!(
            OversamplingConfig::try_from(field_sets::Osr::from(oversampling)),
            Ok(oversampling)
        );

        let output_data_rate = OutputDataRateConfig {
            rate: OutputDataRate::Hz0P05,
        };
        assert_eq!(
            OutputDataRateConfig::try_from(field_sets::Odr::from(output_data_rate)),
            Ok(output_data_rate)
        );

        let command = CommandRegister {
            command: Command::FlushFifo,
        };
        assert_eq!(
            CommandRegister::try_from(field_sets::CmdFieldsIn::from(command)),
            Ok(command)
        );
    }

    #[test]
    fn every_enum_variant_round_trips() {
        for value in [InterruptOutput::PushPull, InterruptOutput::OpenDrain] {
            assert_eq!(InterruptOutput::from(raw::IntOpenDrain::from(value)), value);
        }

        for value in [InterruptLevel::ActiveLow, InterruptLevel::ActiveHigh] {
            assert_eq!(InterruptLevel::from(raw::IntLevel::from(value)), value);
        }

        for value in [PowerMode::Sleep, PowerMode::Forced, PowerMode::Normal] {
            assert_eq!(PowerMode::from(raw::MeasurementMode::from(value)), value);
        }

        for value in [
            Oversampling::X1,
            Oversampling::X2,
            Oversampling::X4,
            Oversampling::X8,
            Oversampling::X16,
            Oversampling::X32,
        ] {
            assert_eq!(
                Oversampling::try_from(raw::Oversampling::from(value)),
                Ok(value)
            );
        }

        for value in [
            OutputDataRate::Hz200,
            OutputDataRate::Hz100,
            OutputDataRate::Hz50,
            OutputDataRate::Hz25,
            OutputDataRate::Hz12P5,
            OutputDataRate::Hz6P25,
            OutputDataRate::Hz3P1,
            OutputDataRate::Hz1P5,
            OutputDataRate::Hz0P78,
            OutputDataRate::Hz0P39,
            OutputDataRate::Hz0P2,
            OutputDataRate::Hz0P1,
            OutputDataRate::Hz0P05,
            OutputDataRate::Hz0P02,
            OutputDataRate::Hz0P01,
            OutputDataRate::Hz0P006,
            OutputDataRate::Hz0P003,
            OutputDataRate::Hz0P0015,
        ] {
            assert_eq!(
                OutputDataRate::try_from(raw::OdrSel::from(value)),
                Ok(value)
            );
        }

        for value in [
            FilterCoefficient::Coefficient0,
            FilterCoefficient::Coefficient1,
            FilterCoefficient::Coefficient3,
            FilterCoefficient::Coefficient7,
            FilterCoefficient::Coefficient15,
            FilterCoefficient::Coefficient31,
            FilterCoefficient::Coefficient63,
            FilterCoefficient::Coefficient127,
        ] {
            assert_eq!(
                FilterCoefficient::from(raw::IirFilterCoefficient::from(value)),
                value
            );
        }

        for value in [Command::Nop, Command::FlushFifo, Command::SoftReset] {
            assert_eq!(Command::try_from(raw::Command::from(value)), Ok(value));
        }
    }

    #[test]
    fn reserved_values_report_their_field() {
        let mut oversampling = field_sets::Osr::new_zero();
        oversampling.set_pressure(raw::Oversampling::Reserved(6));
        assert_eq!(
            OversamplingConfig::try_from(oversampling),
            Err(ReservedValueError::new("osr.pressure", 6))
        );

        let mut oversampling = field_sets::Osr::new_zero();
        oversampling.set_temperature(raw::Oversampling::Reserved(7));
        assert_eq!(
            OversamplingConfig::try_from(oversampling),
            Err(ReservedValueError::new("osr.temperature", 7))
        );

        let mut output_data_rate = field_sets::Odr::new_zero();
        output_data_rate.set_odr_sel(raw::OdrSel::Reserved(31));
        assert_eq!(
            OutputDataRateConfig::try_from(output_data_rate),
            Err(ReservedValueError::new("odr.odr_sel", 31))
        );

        let mut command = field_sets::CmdFieldsIn::new_zero();
        command.set_cmd(raw::Command::Reserved(1));
        assert_eq!(
            CommandRegister::try_from(command),
            Err(ReservedValueError::new("cmd.cmd", 1))
        );
    }
}
