name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show versions
      run: |
        rustc --version
        cargo --version
    - name: Build
      run: cargo build --verbose --all-features --all-targets
    - name: Run tests
      run: cargo test --verbose --no-fail-fast --all-features --all-targets
    - name: Run doc tests
      run: cargo test --verbose --no-fail-fast --all-features --doc

  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --all --check
